.TH MARKSRCRANGE 8 2016-05-25 v1.1.0 "Mark by source ranges"

.SH SUMMARY
.BR MARKSRCRANGE " condenses several `-s <ADDR> -j MARK` ip6tables rules into one, minimizing table walkthrough overhead."

.SH SYNTAX
	ip6tables --table mangle
.br
			--append PREROUTING
.br
.RI "			--source " <PREFIX>
.br
			--target MARKSRCRANGE
.br
.RI "			[--mark-offset " <OFFSET> "]"
.br
.RI "			[--sub-prefix-len " <SUB> "]"

.SH DESCRIPTION
.RI "Will distribute longer sub-prefixes of length /" <SUB> " taken from the shorter " <PREFIX> " across marks " <OFFSET> " through " <OFFSET> " + [number of /" <SUB> " prefixes in " <PREFIX> "] - 1."
.P
.IR <PREFIX> " is an IPv6 CIDR prefix, " <OFFSET> " is an unsigned 32-bit integer that defaults to zero and " <SUB> " is a prefix length that defaults to 128."
.P
The table must be mangle and the chain must be PREROUTING, otherwise ip6tables will be unable to find MARKSRCRANGE. You should be able to include more match logic but --source must be present. If you get cryptic errors, try running dmesg | tail.

